DROP TABLE TASK1_PARTC;
CREATE TABLE TASK1_PARTC(
ROW_ID INT,
ORDER_ID VARCHAR(50),
ORDER_DATE DATE,
SHIP_DATE DATE,
SHIP_MODE VARCHAR(50),
CUSTOMER_ID VARCHAR(50),
CUSTOMER_NAME VARCHAR(100),
SEGMENT VARCHAR(50),
COUNTRY VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTAL_CODE INT,
REGION VARCHAR(50),
PRODUCT_ID VARCHAR(50),
CATEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50),
PRODUCT_NAME VARCHAR(300),
SALES NUMERIC(10,2),
QUANTITY INT,
DISCOUNT NUMERIC(10,2),
PROFIT NUMERIC(10,2)
);

SELECT * FROM TASK1_PARTC ;

SELECT REGION, SUM(SALES) AS TOTAL_SALES
FROM TASK1_PARTC
GROUP BY REGION;

SELECT CATEGORY, SUM(PROFIT) AS TOTAL_PROFIT
FROM TASK1_PARTC
GROUP BY CATEGORY
ORDER BY TOTAL_PROFIT DESC
LIMIT 5;

SELECT
EXTRACT(MONTH FROM ORDER_DATE) AS MONTH_ADDED, 
SUM(SALES) AS TOTAL_SALES
FROM TASK1_PARTC
GROUP BY MONTH_ADDED
ORDER BY MONTH_ADDED;

SELECT DISCOUNT
FROM TASK1_PARTC
ORDER BY DISCOUNT DESC
LIMIT 1;

